version: '3.8'

services:
  promptengine:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: python examples/generate_fuzz.py example_code.py
